name: CHAP_example_02
channels:
  - conda-forge
  - astra-toolbox
  - nodefaults
dependencies:
  - python>=3.9,<3.11
  - astra-toolbox==2.1.0
  - lmfit==1.1.0
  - fabio==2024.9.0
  - matplotlib==3.9.2
  - nexpy==1.0.9
  - nexusformat==1.0.6
  - pip==24.2
  - pydantic==2.7.3
  - tomopy==1.12.2
  - pip:
    - certif-pyspec==1.5.3
