name: CHAP_example_02
channels:
  - conda-forge
  - astra-toolbox
  - nodefaults
dependencies:
  - python>=3.9
  - astra-toolbox==2.1.0
  - lmfit==1.1.0
  - matplotlib==3.7.1
  - nexpy==1.0.4
  - nexusformat==1.0.2
  - pip==22.3.1
  - pydantic==1.10.7
  - sympy==1.12
  - tomopy==1.12.2
  - pip:
    - certif-pyspec==1.5.3

