config:
  inputdir: hollow_pyramid/config
  outputdir: hollow_pyramid/raw/hollow_pyramid

pipeline:

  # Create a simulated stack of tomography images
  - common.YAMLReader:
      filename: tomo_sim_id1a3_pyramid.yaml
      schema: tomo.models.TomoSimConfig
  - tomo.TomoSimFieldProcessor:
      schema: tomo.models.TomoSimField
  # Create the dark field for the simulation
  - tomo.TomoDarkFieldProcessor:
      schema: tomo.models.TomoDarkField
  # Create the bright field for the simulation
  - tomo.TomoBrightFieldProcessor:
      num_image: 10
      schema: tomo.models.TomoBrightField
  # Create the SPEC file for the simulation
  - tomo.TomoSpecProcessor
  - common.FileTreeWriter:
      force_overwrite: true
