config:
  inputdir: /nfs/chess/user/x-cite/data/example_02/hollow_pyramid
  outputdir: ./output
  interactive: false

pipeline:

  # Convert the CHESS style map
  - pipeline.MultiplePipelineItem:
      items:
        - common.SpecReader:
            spec_config:
              station: id3a
              experiment_type: TOMO
              spec_scans:
              - spec_file: data/hollow_pyramid/spec.log
                scan_numbers:
                - 1
            detector_names:
              - sim
            schema: darkfield
        - common.SpecReader:
            spec_config:
              station: id3a
              experiment_type: TOMO
              spec_scans:
              - spec_file: data/hollow_pyramid/spec.log
                scan_numbers:
                - 2
            detector_names:
              - sim
            schema: brightfield
        - common.MapReader:
            filename: map_id3a_pyramid.yaml
            detector_names:
              - sim
            schema: tomofields
        - common.YAMLReader:
            filename: detector_pyramid.yaml
            schema: tomo.models.Detector
  - tomo.TomoCHESSMapConverter

  # Full tomography reconstruction
  - tomo.TomoDataProcessor:
      reduce_data: true
      find_center: true
      reconstruct_data: true
      combine_data: true
      outputdir: saved_figs
      save_figs: 'only'
  - common.NexusWriter:
      filename: hollow_pyramid.nxs
      force_overwrite: true
