name: XCite_example_01
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9,<3.11
  - chessanalysispipeline==2026.04.28
  - fabio==2025.10.0
  - pyfai==2025.12.1
  - matplotlib==3.10.9
  - pip:
    - certif-pyspec==1.5.3
    - chess-scanparsers==2026.02.26
